---
title: "Institutions, power, and inequality"
linktitle: "11: Institutions, power, and inequality"
date: "2020-11-02"
start_date: "2020-11-02"
end_date: "2020-11-06"
menu:
  content:
    parent: Course content
    weight: 11
type: docs
bibliography: "../../static/bib/references.bib"
csl: "../../static/bib/chicago-fullnote-bibliography-no-bib.csl"
pdf: /slides/pmap8141_f20_11-slides.pdf
thumb: /slides/pmap8141_f20_11-slides.png
output:
  blogdown::html_page:
    toc: true
---

## Readings

***Important***: The PDFs of the North and Putnam chapters are posted on iCollege.

- <i class="fas fa-book"></i> Introduction and 5.1–5.10 in *Economy, Society, and Public Policy* [@core-espp]
- <i class="fab fa-twitter-square"></i> [Tweet by Jennifer Victor](https://twitter.com/jennifernvictor/status/1042181507480203264)
- <i class="fas fa-podcast"></i> Freakonomics Radio, ["Earth 2.0: What Would Our Economy Look Like?,"](http://freakonomics.com/podcast/earth-2-0-economics-edition-part-1/) April 12, 2017
- <i class="fas fa-podcast"></i> Planet Money, ["The Dollar at the Center of the World,"](https://www.npr.org/sections/money/2014/07/16/331743569/episode-552-the-dollar-at-the-center-of-the-world) episode 553, July 16, 2014
- <i class="far fa-file-pdf"></i> Chapter 1 in Douglass C. North, *Institutions, Institutional Change, and Economic Performance* [@North:1990] (Remember to use your grad school reading skills here! Don't try to read every word! Skim to understand the argument.)
- <i class="far fa-file-pdf"></i> Chapter 6 in Robert D. Putnam, *Making Democracy Work: Civic Traditions in Modern Italy* [@Putnam:1994] (Remember to use your grad school reading skills here! Don't try to read every word! Skim to understand the argument.)


## Slides

`r blogdown::shortcode("slides")`


## Videos

```{r show-youtube-list, echo=FALSE, results="asis"}
source(here::here("R", "youtube-playlist.R"))

playlist_id <- "PLS6tnpTr39sEHYIB0TE4R-GQvbZ8YpdEI"

videos <- tibble::tribble(
  ~youtube_id, ~title,
  "z0iR95_Bcdk", "Introduction",
  "ISEJVSrxU60", "Institutions",
  "9TpyDtBSB_s", "Institutions, paths, and history"
)

youtube_list(videos, playlist_id)
```


```{cat include=FALSE, eval=FALSE}
Playlist: https://www.youtube.com/playlist?list=PLS6tnpTr39sEHYIB0TE4R-GQvbZ8YpdEI

https://youtu.be/z0iR95_Bcdk
PMAP 8141 • (11) Institutions, power, and inequality: (0) Introduction

Introduction to the class session on institutions

Access the slides and other materials at the course website at https://econf20.classes.andrewheiss.com/content/11-content/


https://youtu.be/ISEJVSrxU60
PMAP 8141 • (11) Institutions, power, and inequality: (1) Institutions

Discussion of different economic approaches to institutions: institutions as rational choices, institutions as constraints, and institutions as equilibria in a game

Access the slides and other materials at the course website at https://econf20.classes.andrewheiss.com/content/11-content/


https://youtu.be/9TpyDtBSB_s
PMAP 8141 • (11) Institutions, power, and inequality: (2) Institutions, paths, and history

Discussion of historical institutionalism, path dependency, and how previous institutions shape future institutions

Access the slides and other materials at the course website at https://econf20.classes.andrewheiss.com/content/11-content/
```
