---
title: "When governments go wrong"
linktitle: "13: When governments go wrong"
date: "2020-11-16"
start_date: "2020-11-16"
end_date: "2020-11-20"
menu:
  content:
    parent: Course content
    weight: 13
type: docs
bibliography: "../../static/bib/references.bib"
csl: "../../static/bib/chicago-fullnote-bibliography-no-bib.csl"
pdf: /slides/pmap8141_f20_13-slides.pdf
thumb: /slides/pmap8141_f20_13-slides.png
output:
  blogdown::html_page:
    toc: true
---

## Readings

**Note: This looks like a lot, but most of these are really short videos or tweets or websites**

- <i class="fab fa-twitter-square"></i> [Noah Smith on why we should worry about race, culture, and politics when thinking about economics](https://twitter.com/noahpinion/status/946446862898282496)
- <i class="fab fa-twitter-square"></i> [Excerpt from Martin Luther King's May 8, 1967 interview with NBC](https://twitter.com/Justinfication/status/981622238234456064)
    - Dr. King gave an in-depth interview with NBC a year before he was assassinated. If you're interested, you can [view the full interview](https://www.nbcnews.com/video/martin-luther-king-jr-speaks-with-nbc-news-11-months-before-assassination-1202163779741), or [read some commentary about his claim that his dream had turned into a nightmare](https://www.theroot.com/dr-martin-luther-king-jr-my-dream-has-turned-into-a-1791257458).
- <i class="fab fa-youtube"></i> Adam Ruins Everything, ["The Disturbing History of the Suburbs"](https://www.youtube.com/watch?v=ETR9qrVS17g), October 4, 2017
- <i class="fas fa-trophy"></i> Play through ["Parable of the Polygons"](https://ncase.me/polygons/) by Nicky Case
- <i class="fas fa-external-link-square-alt"></i> Aaron Glantz and Emmanuel Martinez, ["Kept out: For people of color, banks are shutting the door to homeownership,"](https://www.revealnews.org/article/for-people-of-color-banks-are-shutting-the-door-to-homeownership/) Reveal, February 15, 2018
    - Alternatively, listen to the podcast version of this story, which goes in more depth and is really fantastic: <i class="fas fa-podcast"></i> ["The red line: Racial disparities in lending,"](https://www.revealnews.org/episodes/the-red-line-racial-disparities-in-lending/) Reveal, February 17, 2018
- <i class="fas fa-external-link-square-alt"></i> Emma Roller's interview with Mehrsa Baradaran, ["How the U.S. Government Locked Black Americans Out of Attaining the American Dream,"](https://splinternews.com/how-the-u-s-government-locked-black-americans-out-of-a-1819221197), *Splinter*, October 11, 2017
- <i class="fab fa-twitter-square"></i> [Excerpt from *Amanpour and Company*'s interview with Mehrsa Baradaran](https://twitter.com/amanpourcopbs/status/1283481709070123008?s=21), July 15, 2020
- <i class="fas fa-external-link-square-alt"></i> Dedrick Asante-Muhammad, Chuck Collins, Darrick Hamilton, and Josh Hoxie, ["Ten Solutions to Bridge the Racial Wealth Gap"](https://inequality.org/great-divide/ten-solutions-bridge-racial-wealth-divide/)
- <i class="far fa-file-pdf"></i> Hamilton, et al., ["Umbrellas Don't Make it Rain: Why Studying and Working Hard Isn't Enough for Black Americans"](http://econ.hunter.cuny.edu/wp-content/uploads/2016/03/seminar2016-darity2.pdf) [@HamiltonDarityPrice:2015]
- <i class="fas fa-external-link-square-alt"></i> Mehrsa Baradaran, ["The Real Roots of 'Black Capitalism’'](https://www.nytimes.com/2019/03/31/opinion/nixon-capitalism-blacks.html), *The New York Times*, March 31, 2019

## Optional listening but highly recommended

- <i class="fas fa-podcast"></i> This American Life, ["The Problem We All Live With, Part One,"](https://www.thisamericanlife.org/562/the-problem-we-all-live-with-part-one) episode 562, July 31, 2015
- <i class="fas fa-podcast"></i> This American Life, ["The Problem We All Live With, Part Two,"](https://www.thisamericanlife.org/563/the-problem-we-all-live-with-part-two) episode 563, August 7, 2015


## Slides

`r blogdown::shortcode("slides")`


## Videos

```{r show-youtube-list, echo=FALSE, results="asis"}
source(here::here("R", "youtube-playlist.R"))

playlist_id <- "PLS6tnpTr39sFjCVoP36XaARe2gNS81Xxg"

videos <- tibble::tribble(
  ~youtube_id, ~title,
  "mpheC_1cIoQ", "Introduction",
  "xTPti86Y1oc", "Economics, identity, and whiteness",
  "sb5wjTqSj_s", "Public policy and the institutional legacies of white supremacy"
)

youtube_list(videos, playlist_id)
```


```{cat include=FALSE, eval=FALSE}
Playlist: https://www.youtube.com/playlist?list=PLS6tnpTr39sFjCVoP36XaARe2gNS81Xxg

https://youtu.be/mpheC_1cIoQ
PMAP 8141 • (13) When governments go wrong: (0) Introduction

Introduction to the class session on identity, economics, and white supremacy

Access the slides and other materials at the course website at https://econf20.classes.andrewheiss.com/content/13-content/


https://youtu.be/xTPti86Y1oc
PMAP 8141 • (13) When governments go wrong: (1) Economics, identity, and whiteness

Discussion of how a shared national identity drives the provision of public goods + how different racial and ethnic groups have had to prove their whiteness to access these public goods + case study of how Mormons proved their whiteness

Access the slides and other materials at the course website at https://econf20.classes.andrewheiss.com/content/13-content/


https://youtu.be/sb5wjTqSj_s
PMAP 8141 • (13) When governments go wrong: (2) Public policy and the institutional legacies of white supremacy

Discussion of how racist policies have prevented Black Americans from accumulating assets with federal policies like their white counterparts + overview of different policy proposals designed to boost assets instead of income

Access the slides and other materials at the course website at https://econf20.classes.andrewheiss.com/content/13-content/
```
