---
title: Income and substitution effects
menu:
  resource:
    parent: Guides
type: docs
weight: 4
---

When there is a change in the price of something, we typically change how much of it we buy. If something is a normal good, we'll buy more of it as our income increases. If something is an inferior good, we buy less of it as our income increases.

We can model these changes in prices and changes in behavior with indifference curves and budget lines, which are [covered in great detail in this guide here](/resource/indifference-budget/).

The video embedded below—in addition to all these others—explains the process of doing this:

- <i class="fab fa-youtube"></i> [Example Income and Substitution Effects for Normal and Inferior Goods](https://www.youtube.com/watch?v=pLhh_D5b_Lg)
- <i class="fab fa-youtube"></i> [Explanation of Income and Substitution Effects](https://www.youtube.com/watch?v=ysqGRwvlte0)
- <i class="fab fa-youtube"></i> [EC1002 Chapter 2 Lesson 2 - The Indifference Curve, Substitution, and Income Effect](https://www.youtube.com/watch?v=hDniSzSmpbU) (this one is long and detailed, but still helpful, especially around minute 21)

<div class="embed-responsive embed-responsive-16by9">
<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/tXMRnDAbKVg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
