---
title: Assignment overview
menu:
  assignment:
    parent: Overview
    weight: 1
type: docs
weight: 1
output:
  blogdown::html_page:
    toc: true
---


The main goals of this class are to help you understand, speak, and do economics. Each type of assignment in this class is designed to help you achieve one or more of these goals.


## Participation

When I teach this course in face-to-face settings, I make it as interactive, personable, and fun as possible, using all sorts of simulations and in-class games and activities. In an asynchronous online setting, this is sadly not possible. These activities are fantastic not only for understanding core economic principles, but because they allow for increased social interaction, which helps with learning.

Research about online courses consistently finds that [learning requires social interaction to be successful](https://www.tandfonline.com/doi/full/10.1080/15512169.2016.1155994). In fact, one of the greatest predictors of success is whether students build relationships with their classmates and their professor. This is true for **both** online classes and face-to-face classes! It's entirely possible to take a face-to-face class and have almost no social interaction. The worst, most useless class I ever took as an undergraduate was a required Intro to US History class that met twice a week for two hours in a massive auditorium with 900 (!!!) other students. It was awful and I learned nothing.

Facilitating, measuring, and quantifying social interaction in an online course, however, is fraught with difficulty. I do not want to create an inorganic forum where you must do things like leave two comments of at least 15 words every week, or other things that begin to approach busywork. The temptation to just phone in participation is too great (I would *absolutely* phone it in if I were taking a class with similar requirements: "great post i agree entirely with the premise of your reflection and synthesis thank you"—15 words, boom.).

There are two elements of this course that are designed to make social interaction more organic and real and also allow you to work through economic principles together: (1) Slack and (2) weekly reports.

### Slack

To help facilitate online interaction, we will use Slack for communication. The iCollege forums are stodgy, overly formal, and clunky. Slack is not. 

Access the class workspace [here](https://gsueconf2020.slack.com), or click on the [<i class="fab fa-slack"></i>](https://gsueconf2020.slack.com) icon in the header of this page. If you're unfamiliar with Slack, [scroll through Slack's official demo here](https://slackdemo.com/).

There are three public channels in our class workspace:

- `#welcome`: Introduce yourself here after you join the workspace.
- `#general`: Post and talk about general things related to the class and economics in general. Find a neat news story related to principal-agent problems? See an example of a stag hunt game in real life? Wonder why a problem set isn't posted yet? Share and ask those things here.
- `#help`: Ask specific questions about problem sets and other assignments here.

Feel free to create your own channels as well. For instance, if you want to use Slack to work on your weekly reports in your groups, create a channel. 

You can also direct message me to contact me directly.

In general, interact with me and your classmates through Slack! Don't lurk in silence in the shadows. (Don't overshare either and spam the `#general` channel in Slack, but in my experience there's little risk of that). *Do* reach out and talk to your classmates (and me!). 

In other online classes I have taught, I have found that a key predictor of success is how often students communicate with me and between themselves. Ask questions on Slack. If you see someone's question there and you know how to help, answer! 

**You're not going to be graded on Slack usage.** I will not watch to see who is active or count likes or responses or anything like that. If you want to opt out entirely and never use it, feel free to do so. You'll just miss out on a lot of public class-related conversation, possible avenues for help, and a pretty quick way to get in contact with me.


### Weekly reports

To (1) demonstrate to me what you're learning in the class, and (2) facilitate interaction with others in the class, you will turn in a short weekly report by **11:59 PM every Monday**.

You will complete this report in groups of 5–6 that I will randomly assign at the beginning of the semester. 

Each of you will take a specific role each week. You must play each role at least once during the semester. Figure out amongst yourselves who wants to do what and when. We're in a pandemic and your schedules are all wildly messed up right now. Please be respectful and generous with your groupmates in negotiating and scheduling your roles. 

To help you with this report, [I've provided a template here](/assignment/weekly-reports/). I'd recommend using Google Docs and adding content to the report throughout the week.

There are four roles for each weekly report, each with different responsibilities. **If your group has more than 4 people, the extra people will double up on a role.**

**Role 1: Analyzer**

Summarize and analyze the week's readings and videos. Complete the summary and analysis by Wednesday if possible to give others time to build on your work. This should be written in a bulleted format including the three points below. Each bullet point should be 2–5 complete sentences (that's short!).

- What are the main economic principles from this week's content? Concisely synthesize the assigned readings.
- Describe where the readings' content, theory, or assumptions diverge. What does one reading add to or detract from the others?
- Critique one of more of the readings. Challenge an assumption, argument, or method of analysis.

**Role 2: Evaluator**

Evaluate and review the Analyzer's analysis. What are the strengths of the summary and critique? What are the gaps in the analysis? Did you come to similar or different conclusions? Simply agreeing is not acceptable. If you do agree with the Analyzer, then expand their summary and analysis. Limit your response to 250 words *at most* (that's roughly one page, double spaced in Word).

**Role 3: Reporter**

Find a current event and apply the week's principles to it. Build on the assigned readings and the Analyzer's analysis. Limit your response to 250 words *at most* (that's roughly one page, double spaced in Word) and provide a link to the article.

**Role 4: Problem set-er**

The problem setter's role changes depending on when problem sets are due. I will provide the answers keys for each problem set after it is due. 

1. In weeks that do not immediately follow a problem set deadline (typically even weeks like session 2), you don't have much to do. I encourage you to work on your problem set together as a group or check each other's answers or ask each other questions, but this is not required.

2. In weeks that immediately follow turning in a problem set (typically odd weeks like session 3), you will facilitate a review of the problem set answers between your group members This can be done via Slack, e-mail, Webex, WhatsApp, FaceTime, Skype, carrier pigeon, or any other platform. This discussion can be as long or as short as you want it to be. Taking on this role does not mean that you must be an expert in the questions or know exactly how to answer them—it just means that you'll lead the discussion.

    Answer these two questions after the review:

    - Which problem set question was the most difficult?
    - What questions does your group still have?

**Grading**

I will grade these reports with a check system:

- ✔+: (*12 points (120%) in gradebook*) Report shows phenomenal thought and deep engagement with the course content. I will not assign these often.
- ✔: (*10 points (100%) in gradebook*) Report is thoughtful, well-written, and shows engagement with the course content. This is the expected level of performance.
- ✔−: (*5 points (50%) in gradebook*) Report is hastily composed, too short, and/or only cursorily engages with the course content. This grade signals that you need to improve next time. I will hopefully not assign these often.

Notice that is essentially a pass/fail or completion-based system. I'm not grading your writing ability, I'm not counting the exact number of words you're writing, and I'm not looking for encyclopedic citations of every single reading to prove that you did indeed read everything. I'm looking for thoughtful engagement, that's all. Do good work and you'll get a ✓.

You will turn these reports in via iCollege. Only one person per group needs to turn it in.


## Problem sets

To practice solving microeconomic problems you will complete a series of 8 problem sets. Many of the questions on these assignments will come from *Economy, Society, and Public Policy*, some will come from previous courses, and others will come from my head.

You need to show that you made a good faith effort to work each question. I will not grade these in detail—if you get stuck on a particularly tricky question, don't panic or worry! I provide you with all the answer keys and you will go over the answers as part of your weekly report.

The problem sets will be graded using a check system:

- ✔+: (*23 points (115%) in gradebook*)  Problem set is 100% completed. Every question was attempted and answered, and all answers are correct. Work is exceptional. I will not assign these often.
- ✔: (*20 points (100%) in gradebook*) Problem set is 70–99% complete and most answers are correct. **This is the expected level of performance.**
- ✔−: (*10 points (50%) in gradebook*) Problem set is less than 70% complete and/or most answers are incorrect. This indicates that you need to improve next time. I will hopefully not asisgn these often.

You may (and should!) work together on the problem sets, but *you must turn in your own answers.*

You will turn these problem sets in via iCollege. 


## Exams

There will be two exams covering (1) capitalism, markets, power, and institutions and core economic models, and (2) market failures and government intervention in the economy.

You will take these exams online through iCollege. The exams will be timed, but you can use notes and readings and [the Google](https://www.youtube.com/watch?v=AQ45fO1uiOQ). You must take the exams on your own though, and not talk to anyone about them.

Study guides for each exam will be posted in [the resources section](/resource/).
