---
title: "Weekly report template"
linktitle: "Weekly report template"
date: "2020-05-11"
due_date: "2020-05-11"
due_time: "11:59 PM"
menu:
  assignment:
    parent: Weekly reports
    weight: -10
type: docs
weight: -10
editor_options: 
  chunk_output_type: console
---

Here's a template to use for your weekly reports. 

This is also available as a [Google Docs template here](https://docs.google.com/document/d/12DOYR5e878FuzX9UGZD0BCfikcIsFrZtmIvlZihFcdQ/template/preview).

---

### Weekly report for DATE

**Sessions covered**: Session X

**Roles**

- Analyzer: NAME
- Evaluator: NAME
- Reporter: NAME
- Problem set-er: NAME

**Analysis**

Summarize and analyze the week's readings and videos. Complete the summary and analysis by Wednesday if possible to give others time to build on your work. This should be written in a bulleted format including the three points below. Each bullet point should be 2–5 complete sentences (that's short!).

- What are the main economic principles from this week's content? Concisely synthesize the assigned readings.
- Describe where the readings' content, theory, or assumptions diverge. What does one reading add to or detract from the others?
- Critique one of more of the readings. Challenge an assumption, argument, or method of analysis.

**Evaluation**

Evaluate and review the Analyzer's analysis. What are the strengths of the summary and critique? What are the gaps in the analysis? Did you come to similar or different conclusions? Simply agreeing is not acceptable. If you do agree with the Analyzer, then expand their summary and analysis. Limit your response to 250 words *at most* (that's roughly one page, double spaced in Word).

**Reporting**

Find a current event and apply the week's principles to it. Build on the assigned readings and the Analyzer's analysis. Limit your response to 250 words *at most* (that's roughly one page, double spaced in Word) and provide a link to the article.

**Problem set review**

The problem setter's role changes depending on when problem sets are due. I will provide the answers keys for each problem set after it is due. 

1. In weeks that do not immediately follow a problem set deadline (typically even weeks like session 2), you don't have much to do. I encourage you to work on your problem set together as a group or check each other's answers or ask each other questions, but this is not required.

2. In weeks that immediately follow turning in a problem set (typically odd weeks like session 3), you will facilitate a review of the problem set answers between your group members This can be done via Slack, e-mail, Webex, WhatsApp, FaceTime, Skype, carrier pigeon, or any other platform. This discussion can be as long or as short as you want it to be. Taking on this role does not mean that you must be an expert in the questions or know exactly how to answer them—it just means that you'll lead the discussion.

    Answer these two questions after the review:

    - Which problem set question was the most difficult?
    - What questions does your group still have?
